# Generated by Django 4.0.3 on 2022-06-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactprofile',
            old_name='Message',
            new_name='message',
        ),
    ]
